'\" t
.\"    Title: random
.\"     Date: 20/03/2022
.\"   Manual: Пользовательские команды
.\" Language: Russian
.\"
.TH random 1 "март 2022" "random 0.5.7"
.
.
.\" ====================================================================
.SH "ИМЯ"
.\" ====================================================================
.
random \- генератор случайных последовательностей символов.
.
.
.\" ====================================================================
.SH "ОБЗОР"
.\" ====================================================================
.
.SY random
.OP число
.YS
.SY random
.B \-h
.SY random
.B \-\-help
.YS
.
.
.\" ====================================================================
.SH ОПИСАНИЕ
.\" ====================================================================
.
Программа
.B random
используется для генерации случайных последовательностей символов с
заданной длинной.
.
Когда программа завершется,
она выдает на стандартный вывод последовательность случайных символов
заданной длины.
.PP
В генераторе используются строчные и прописные буквы,
а также цифры.
.PP
Можно использовать в скриптах,
для присвоения переменным случайных последовательностей символов.
.PP
Примеры команд приведены в разделе
.IR ПРИМЕРЫ .
.
.
.\" ====================================================================
.SH ПАРАМЕТРЫ
.\" ====================================================================
.
.TP
.B число
Длина генерируемого случайного значения.
Числовое значение больше 0.
.
.TP
.B \-h
.TQ
.BI \-\-help
Показать справку по использованию программы и завершить его работу.
.
.
.\" ====================================================================
.SH ПРИМЕРЫ
.\" ====================================================================
.
.TP
.EX
.B random\~8
.EE
Команда используется при вызове из консоли.
Генерируется случайная последовательность из алфавитно-цифрового кода
длинной 8 символов.
.
Пример вывода скрипта по завершении работы -
.IR 8YLsd9s0 .
.
.TP
.EX
.B x=\(lq$(random 8)\(rq
.EE
Пример использования в скриптах для присвоения переменным случайных
последовательностей.
.
Переменной
.B x
будет присвоена случайная последовательность символов.
